language: cpp
compiler:
  - gcc
  - clang
before_install:
 - sudo add-apt-repository -y ppa:azat/boost-unofficial
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost1.53-all-dev
 - git submodule update --init --recursive
script:
 - scons
 - x86/Release/tests
