# Travis CI script to invoke coveralls.io coverage reporting
# (C) 2015 Niall Douglas

language: cpp
notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always

env:
  # Coveralls.io API key
  secure: "LU8flpdvLjaFIVgy8oqhHzy92AUPRgw3bRv+/Q91fnWNrvbeRVMEOj+vML+zDS7iU3L2ZbppNf/1YkavGhHh9HfD8PC0dYPEmU0xjS/3WdoKxMd0MCYUZxQ+6zgx3GLgZS2NxciVlruZSs9Q+hKbguvvjwGGSVin6LlMmC2KqGA="
  matrix:
    - _="GCC 4.8 + Standalone unit/functional tests coverage" VALGRIND=0 CCFLAGS="-fprofile-arcs -ftest-coverage -DBOOST_AFIO_COMPILING_FOR_GCOV -DNDEBUG" UNIT_TESTS=1 DEBUG=1 GCCVER="-4.8" GCOV=1

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - if [ $GCCVER != "" ]; then sudo apt-get install -qq g++$GCCVER; fi
 - git submodule update --init --recursive
 - sudo apt-get install -qq libboost-all-dev

script:
 - CFLAGS="$CFLAGS -g -O2 -std=c++11 test/test_all.cpp detail/SpookyV2.cpp -Iinclude -Itest -DBOOST_AFIO_RUNNING_IN_CI=1 -lboost_filesystem -lboost_system -lpthread"
 - if [ $GCOV -eq 1 ]; then LINKFLAGS="$LINKFLAGS -lgcov"; fi
 - if [ $GCOV -eq 1 ]; then set -x; fi
 - cd test
 - bash ./test_file_glob.sh
 - cd ..
 - g++$GCCVER -o test_all_gcov $CFLAGS $LINKFLAGS
 - ./test_all_gcov

after_success:
 - if [ $GCOV -eq 1 ]; then bash -x test/update_coveralls.sh `pwd`; fi
