# version format
version: 1.40.{build}-{branch}
 
# branches to build
branches:
  # blacklist
  except:
    - gh-pages
skip_tags: true
 
# Operating system (build VM template)
os: Visual Studio 2015
init:
  - git config --global core.longpaths true

clone_folder: c:\boost.afio
platform: x64 
configuration: Release

before_build:
  - git submodule update --init --recursive
  - git submodule foreach git checkout master
  - git submodule foreach git pull origin master
  - cd test
  - call test_file_glob.bat
  - cd ..
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
build_script:
  - standalone_alltests_msvc.bat
after_build:

before_test:
test_script:
#  - test_all.exe --reporter junit --out results_all.xml
  - test_all.exe
after_test:
#  - type results_all.xml

on_success:
on_failure:
on_finish:
